server:
  port: 7004
spring:
  application:
    name: sca-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: sca-account-consumer
        uri: lb://sca-account-consumer
        predicates:
        - Path=/sca-account/**
  main:
    allow-bean-definition-overriding: true